# Generated by Django 4.2 on 2023-05-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("win_team", models.IntegerField(null=True, verbose_name="win_team")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is_active"),
                ),
                ("user_info", models.TextField(default="", verbose_name="user_info")),
                ("bet_rate", models.TextField(null=True, verbose_name="bet_rate")),
                ("user_rate", models.TextField(null=True, verbose_name="user_rate")),
            ],
        ),
        migrations.CreateModel(
            name="Games",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("select_1", models.IntegerField(null=True)),
                ("select_2", models.IntegerField(null=True)),
                ("select_3", models.IntegerField(null=True)),
                ("point_1", models.IntegerField(null=True)),
                ("point_2", models.IntegerField(null=True)),
                ("point_3", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameUser",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("bet_point", models.IntegerField(default=0, verbose_name="bet_point")),
                ("bet_team", models.IntegerField(default=0, verbose_name="bet_team")),
            ],
        ),
        migrations.CreateModel(
            name="GetGameIds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ids", models.TextField(verbose_name="ids")),
            ],
        ),
        migrations.CreateModel(
            name="GetUser",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("password", models.CharField(max_length=20, verbose_name="password")),
                ("student", models.CharField(max_length=9, verbose_name="student")),
            ],
        ),
        migrations.CreateModel(
            name="GetUserId",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HashUser",
            fields=[
                ("hash", models.TextField(verbose_name="hash")),
                (
                    "email",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="email",
                    ),
                ),
                ("password", models.CharField(max_length=20, verbose_name="password")),
                ("student_number", models.IntegerField(verbose_name="student_number")),
                ("name", models.CharField(max_length=4, verbose_name="name")),
            ],
        ),
        migrations.CreateModel(
            name="Minigame",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("bet_point", models.IntegerField(default=0, verbose_name="bet_point")),
                ("is_win", models.BooleanField(default=False, verbose_name="is_win")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="email",
                    ),
                ),
                ("password", models.CharField(max_length=20, verbose_name="password")),
                ("student_number", models.IntegerField(verbose_name="student_number")),
                ("name", models.CharField(max_length=4, verbose_name="name")),
                ("point", models.IntegerField(default=30000, verbose_name="point")),
                ("minigame_count", models.IntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("select_1", models.IntegerField(null=True)),
                ("select_2", models.IntegerField(null=True)),
                ("select_3", models.IntegerField(null=True)),
                ("point_1", models.IntegerField(null=True)),
                ("point_2", models.IntegerField(null=True)),
                ("point_3", models.IntegerField(null=True)),
                ("is_vote", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]

# save 