# Generated by Django 4.2 on 2023-04-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("point", models.IntegerField()),
                ("studentnumber", models.IntegerField()),
                ("name", models.CharField(max_length=4)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
