# Generated by Django 4.2 on 2023-04-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_user_clas_user_grade_user_name_user_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="clas",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="no",
            field=models.IntegerField(default=0),
        ),
    ]
